
name: ipywidgethello_docs
channels:
  - conda-forge
dependencies:
- python=3.5
- nodejs
- sphinx
- nbsphinx
- jupyter_sphinx
# TODO: Add any documentation dependencies you want installed by coda on RTD here
